---
title       : Spotify Music Recommendation
subtitle    : A little app that try to help people
author      : Evangeline Monica a/p Rajen(S2123599),
              Yong Hua Qi(U2102791),
              Leow Jia Sheng(U2102826)
              Mohammad Nazrin bin Nohammad Nazri Nages(U2000443)
job         : WIA 1007 Assignment Group 22 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
logo        : spotify.jpeg
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides


---

## Introduction

As our WIA1007 assignment, We choose to make a Music Recommendation App as our project

Name as Spotify Music Recommendation

Our member list

Evangeline Monica   &nbsp; S2123599         

Yong Hua Qi   &nbsp;   U2102791             

Leow Jia Sheng   &nbsp;  U2102826             

Mohammad Nazrin bin
Nohammad Nazri Nages  &nbsp;   U2000443       

--- .class #id 

## The dataset we used

```{r, 'datatable1', echo=FALSE, warning=FALSE,cache=FALSE,results='asis'}

cat('<iframe src="top10s.html" width=50% height=50% allowtransparency="true"> </iframe>')

```

--- .class #id 
## How to used this app

1.The user can select their favourite music genre.There are a lot of music genre such as Acoustic Pop,Alaska India,Alternative R&B and so on.

2.Furthermore,the user can also select their favourite artist. For example,Khalid,Sia,Adam Lambert and so on.

3.Then,our system will display the Songs that the user may like as well as the artist,genre and even the year of published of the song.

4.Last but not least,our application will also come out with the graph that are showing the popularity of each track of your favourite.

5.Finally,the user can clearfully know the song recommendation and then choose a song he love to enjoy the music in thier lives.



--- 
## The limitations for this app
1.The limitations of this link is the total song in this application is not enough.

2.Moreover,the user can't get the link to listen to the song they want so that they need to get the song by themselves through the other platform like Youtube and Spotify.


Thank you
